/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniAttempt_1_19_2018_InfixToPostfixTesterJni */

#ifndef _Included_JniAttempt_1_19_2018_InfixToPostfixTesterJni
#define _Included_JniAttempt_1_19_2018_InfixToPostfixTesterJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniAttempt_1_19_2018_InfixToPostfixTesterJni
 * Method:    getPostfix
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniAttempt_11_119_12018_InfixToPostfixTesterJni_getPostfix
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
